language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t mchen/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true mchen/docker-react npm run test